SHELL = /bin/sh
FLAGS = -Wall
CC = g++

all:    TwoPipesTwoChildren TwoPipesThreeChildren DynPipe  

TwoPipesTwoChildren:     TwoPipesTwoChildren.cpp
	$(CC) $(FLAGS) -o $@ TwoPipesTwoChildren.cpp

TwoPipesThreeChildren:     TwoPipesThreeChildren.cpp
	$(CC) $(FLAGS) -o $@ TwoPipesThreeChildren.cpp



DynPipe:     DynPipe.c
	$(CC) $(FLAGS) -o $@ DynPipe.cclean:
	rm TwoPipesTwoChildren TwoPipesThreeChildren DynPipe